config/routes.rb
ForThree::Application.routes.draw do

  resources :weeks
  resources :weekly_stats
  resources :teams
  resources :yahoo_receiver, :only => 'index'
  resources :powerindex, :only => 'index'
  match 'matchup' => 'static#headToHead'
  
  match ':action' => 'static#:action'
  root :to => 'weeks#index'
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  # GET /weeks
  # GET /weeks.json
  def index

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weeks }
    end
  end

  # GET /weeks/1
  # GET /weeks/1.json
  def show
    @week = params[:id]

    @weekStats = WeeklyStat.find_all_by_week_number(params[:id])

    @teamNames = [];
    @tpm = []; 
    @assists = [];
    @blocks = []; 
    @fgp = []; 
    @ftp = []; 
    @rebounds = []; 
    @steals = []; 
    @points = []; 
    @turnovers = []; 

    @weekStats.each do |week| 
      @teamNames.append(week.team.name); 
      @tpm.append(week.three_pointers_made); 
      @assists.append(week.assists);
      @blocks.append(week.blocks); 
      @fgp.append(week.field_goal_percentage); 
      @ftp.append(week.free_throw_percentage); 
      @rebounds.append(week.rebounds); 
      @steals.append(week.steals); 
      @points.append(week.total_points);
      @turnovers.append(week.turnovers); 
    end


    @weekStats = @weekStats.to_json;    
    @teamNames = @teamNames.to_json; 
    
    @client_data = [@tpm, @assists, @blocks, @fgp, @ftp, @rebounds, @steals, @points, @turnovers].to_json;
    @dataMap = {
      0 => "3PM", 
      1 => "Assists", 
      2 => "Blocks", 
      3 => "FG%", 
      4 => "FT%", 
      5 => "Rebounds", 
      6 => "Steals", 
      7 => "Points", 
      8 => "TO"
    }.to_json
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @week }
    end
  end


end

app/helpers/weeks_helper.rb
module WeeksHelper
end

app/views/weeks/index.html.haml
.hero-unit
  %h1 
    Select a week

    .dropdown
      %a{:class => "dropdown-toggle btn btn-primary btn-large", :id => "dLabel", :role => "button", "data-toggle" => "dropdown", "data-target" => "#", :href => "#"}
        Select a Week
        %b.caret
      %ul.dropdown-menu{:role => "menu", "aria-labelledby" => "dLabel"}
        - (1..26).each do |week|
          %a{:href => "weeks/#{week}"} Week #{week}

app/views/weeks/show.html.haml
%p#notice #{notice}

%h1.offset6 Week  #{@week}


.span3.offset1
	%ul.nav.nav-list#team_name_checkboxes


.span8
	#box_plot.span8

	#weekly_stat_list_placeholder

	.well
		%legend Add Research Here:
		%input#research_input{:type => "text", :placeholder => "[Team Name] [FG%] [FT%] [3PTM] [PTS] [REB] [AST] [ST] [BLK] [TO]", :style => "width: 100%"}
		%button#add_research_button.btn.btn-large{:href => "#myModal"} Add data

	%script{:type => "text/template", :id => "weekly_stat_template"}
		%td [[= team.attributes.name ]]
		%td [[= field_goal_percentage ]]
		%td [[= free_throw_percentage ]]		
		%td [[= three_pointers_made ]]
		%td [[= total_points ]] 
		%td [[= rebounds ]] 
		%td [[= assists ]]
		%td [[= steals ]] 
		%td [[= blocks ]]
		%td [[= turnovers]]

	%input{ :type => "hidden", :value => "#{@week}", :id => "week_number"}

	= link_to 'Back', weeks_path


= content_for :page_js do 
	:javascript
		var data = JSON.parse('#{raw @client_data}');
		var dataMap = JSON.parse('#{raw @dataMap}');
		loadBoxAndWhisker(data, dataMap);
		loadCheckboxes(JSON.parse('#{raw @teamNames}'));	
		loadWeeklyStatViews(); 
		renderPage(); 
		$('.team_li').click(teamClickHandler);