config/routes.rb
ForThree::Application.routes.draw do

  resources :weeks
  resources :weekly_stats
  resources :teams
  resources :yahoo_receiver, :only => 'index'
  resources :powerindex, :only => 'index'
  match 'matchup' => 'static#headToHead'
  
  match ':action' => 'static#:action'
  root :to => 'weeks#index'
end

app/models/weekly_stat.rb
class WeeklyStat < ActiveRecord::Base
	belongs_to :team
  attr_accessible  :three_pointers_made
  attr_accessible  :assists
  attr_accessible  :blocks
  attr_accessible  :field_goal_percentage
  attr_accessible  :free_throw_percentage
  attr_accessible  :rebounds
  attr_accessible  :steals
  attr_accessible  :team_id
  attr_accessible  :week_number
  attr_accessible  :turnovers
  attr_accessible  :total_points

  validates :team_id, { :presence => true }  

  validates_uniqueness_of :week_number, :scope => :team_id
end

app/controllers/weekly_stats_controller.rb
class WeeklyStatsController < ApplicationController
  # GET /weekly_stats
  # GET /weekly_stats.json
  def index

    week_number = params[:week_number]

    if week_number.nil?
      @weekly_stats = WeeklyStat.all
    else 
      @weekly_stats = WeeklyStat.find_all_by_week_number(week_number)
    end

    puts @weekly_stats.size

    puts '******************************************************'
    puts @weekly_stats.to_json(:include => [:team])
    puts '******************************************************'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weekly_stats.to_json(:include => [:team]) }
      format.js { render json: @weekly_stats.to_json(:include => [:team]) }      
    end
  end

  # GET /weekly_stats/1
  # GET /weekly_stats/1.json
  def show
    @weekly_stat = WeeklyStat.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @weekly_stat.to_json(:include => [:team]) }
      format.js { render :layout=>false }
    end
  end

  # GET /weekly_stats/new
  # GET /weekly_stats/new.json
  def new
    @weekly_stat = WeeklyStat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @weekly_stat }
    end
  end

  # GET /weekly_stats/1/edit
  def edit
    @weekly_stat = WeeklyStat.find(params[:id])
  end

  # POST /weekly_stats
  # POST /weekly_stats.json
  def create

    puts '******************** Creating Weekly Stats ***************************'
    puts params[:team]
    
    teamName = params[:team][:name]
    puts(teamName)


    team = Team.find_by_name(teamName)
    if team.nil? && !teamName.nil?
      team = Team.create(:name => teamName)
    end

    puts 'TEAM: ' + team.id.to_s
    
    @weekly_stat = WeeklyStat.find_by_team_id_and_week_number(team.id, params[:weekly_stat][:week_number])
    #stats = WeeklyStat.where("team_id = ? AND week_number = ?", team.id, params[:weekly_stat][:week_number])
    updateSuccessful = false

    if (@weekly_stat.nil?)
      puts '############# No existing stat found :( ###############################'            
      @weekly_stat = WeeklyStat.new(params[:weekly_stat])
      @weekly_stat.team = team
      updateSuccessful = @weekly_stat.save
    else 
      puts '############# FOUND EXISTING STAT RECORD ###############################'   
      updateSuccessful = @weekly_stat.update_attributes(params[:weekly_stat])   
    end


    respond_to do |format|
      if updateSuccessful
        format.html { redirect_to @weekly_stat, notice: 'Weekly stat was successfully created.' }
        format.json { render json: @weekly_stat, status: :created, location: @weekly_stat }
      else
        format.html { render action: "new" }
        format.json { render json: @weekly_stat.errors, status: :unprocessable_entity }
      end
    end
  end



  # PUT /weekly_stats/1
  # PUT /weekly_stats/1.json
  def update
    @weekly_stat = WeeklyStat.find(params[:id])

    respond_to do |format|
      if @weekly_stat.update_attributes(params[:weekly_stat])
        format.html { redirect_to @weekly_stat, notice: 'Weekly stat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @weekly_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weekly_stats/1
  # DELETE /weekly_stats/1.json
  def destroy
    @weekly_stat = WeeklyStat.find(params[:id])
    @weekly_stat.destroy

    respond_to do |format|
      format.html { redirect_to weekly_stats_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/weekly_stats_helper.rb
module WeeklyStatsHelper
end

app/views/weekly_stats/_form.html.erb
<%= form_for(@weekly_stat) do |f| %>
  <% if @weekly_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weekly_stat.errors.count, "error") %> prohibited this weekly_stat from being saved:</h2>

      <ul>
      <% @weekly_stat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :three_pointers_made %><br />
    <%= f.number_field :three_pointers_made %>
  </div>
  <div class="field">
    <%= f.label :blocks %><br />
    <%= f.number_field :blocks %>
  </div>
  <div class="field">
    <%= f.label :field_goal_percentage %><br />
    <%= f.text_field :field_goal_percentage %>
  </div>
  <div class="field">
    <%= f.label :free_throw_percentage %><br />
    <%= f.text_field :free_throw_percentage %>
  </div>
  <div class="field">
    <%= f.label :rebounds %><br />
    <%= f.number_field :rebounds %>
  </div>
  <div class="field">
    <%= f.label :steals %><br />
    <%= f.number_field :steals %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br />
    <%= f.number_field :team_id %>
  </div>
  <div class="field">
    <%= f.label :turnovers %><br />
    <%= f.number_field :turnovers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weekly_stats/edit.html.erb
<h1>Editing weekly_stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @weekly_stat %> |
<%= link_to 'Back', weekly_stats_path %>

app/views/weekly_stats/index.html.erb
<h1>Listing weekly_stats</h1>

<table>
  <tr>
    <th>Three pointers made</th>
    <th>Blocks</th>
    <th>Field goal percentage</th>
    <th>Free throw percentage</th>
    <th>Rebounds</th>
    <th>Steals</th>
    <th>Team</th>
    <th>Turnovers</th>
    <th>Week Number</th>
    <th></th>
    <th></th>
  </tr>

<% @weekly_stats.each do |weekly_stat| %>
  <tr>
    <td><%= weekly_stat.three_pointers_made %></td>
    <td><%= weekly_stat.blocks %></td>
    <td><%= weekly_stat.field_goal_percentage %></td>
    <td><%= weekly_stat.free_throw_percentage %></td>
    <td><%= weekly_stat.rebounds %></td>
    <td><%= weekly_stat.steals %></td>
    <td><%= weekly_stat.team_id %></td>
    <td><%= weekly_stat.turnovers %></td>
    <td><%= weekly_stat.week_number %></td>
    <td><%= link_to 'Show', weekly_stat %></td>
    <td><%= link_to 'Edit', edit_weekly_stat_path(weekly_stat) %></td>
    <td><%= link_to 'Destroy', weekly_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Weekly stat', new_weekly_stat_path %>

app/views/weekly_stats/new.html.erb
<h1>New weekly_stat</h1>

<%= render 'form' %>

<%= link_to 'Back', weekly_stats_path %>

app/views/weekly_stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Three pointers made:</b>
  <%= @weekly_stat.three_pointers_made %>
</p>

<p>
  <b>Blocks:</b>
  <%= @weekly_stat.blocks %>
</p>

<p>
  <b>Field goal percentage:</b>
  <%= @weekly_stat.field_goal_percentage %>
</p>

<p>
  <b>Free throw percentage:</b>
  <%= @weekly_stat.free_throw_percentage %>
</p>

<p>
  <b>Rebounds:</b>
  <%= @weekly_stat.rebounds %>
</p>

<p>
  <b>Steals:</b>
  <%= @weekly_stat.steals %>
</p>

<p>
  <b>Team:</b>
  <%= @weekly_stat.team_id %>
</p>

<p>
  <b>Turnovers:</b>
  <%= @weekly_stat.turnovers %>
</p>

<%= link_to 'Edit', edit_weekly_stat_path(@weekly_stat) %> |
<%= link_to 'Back', weekly_stats_path %>